mutation InsertHabit($userId: Int!, $name: String!, $habitType: habit_type_enum!, $time: timetz, $date: date) {
	insert_habit_one(
		object: { user_id: $userId, name: $name, habit_type: $habitType, time_created: $time, created_at: $date }
	) {
		habit_id
		name
		created_at
		habit_type
		time_created
		user_id
	}
}

mutation DeleteHabitByPK($habitId: Int!) {
	delete_habit_by_pk(habit_id: $habitId) {
		habit_id
	}
}
