query GetHabitsByUserIdAndDate($userId: Int!, $date: date!, $offset: Int) {
	habit(where: { user_id: { _eq: $userId }, created_at: { _eq: $date } }, offset: $offset) {
		habit_id
		created_at
		name
		time_created
		habit_type
		user_id
	}
}
